### PR TITLE
➕ Add License Text

### PR DESCRIPTION
**Pull request by AYIDouble**
This is important for many Devs who are working on Open Source Software.

### CODE REVIEW

**Comment by dlemstra** [comment]
I wonder if this is the correct spot. And it is not clear in your description that Magick.NET is not the same as ImageMagick.

**Comment by AYIDouble** [comment]
I assumed that Magick.NET uses "ImageMagick".
Isn't Magick.NET just a Wrapper written in C# who uses ImageMagick?
The Reason why I find it important, that the license can clearly be seen on the first sight is because of this: [https://github.com/Debian/dcs/pull/95](https://github.com/Debian/dcs/pull/95)

``` For dcs, it’s important that all files can be produced using open source software. ```

**Comment by dabutvin** [comment]
Hi @AYIDouble , thanks for starting this conversation! 

I definitely think this is a worthwhile effort and it would be great to make it more obvious at a glance what components ImgBot is built on top of. That being said, I have a few concerns.

 - There are many components that we rely on for this project that are not listed such as LibGit2Sharp, bootstrap, BouncyCastle, Newtonsoft.Json, and many others
 - The license listed next to the projects is accurate today, but I am concerned about them quickly getting out of date. If a project license changes in future versions (say from MIT to Apache) and we upgrade, but leave this behind we could be communicating the wrong license here
 - Magick.NET is not the same as ImageMagick, these are separate projects and are licensed independently. This will be the case of almost every project. The project we depend on will have dependencies on other projects which may have dependencies on other projects.

Here is what I propose, let me know your thoughts. 

1. Make a separate MD file for this data since it will be grow considerably large. We can add a link to the file from the ReadMe with a brief explanation to make it more discoverable
2. List every component we depend on in the file by checking the `Web/package.json` `dependencies` as well as the `*.csproj` `<PackageReference>` nodes.
3. I'm suggesting we limit the data provided to a URL to the GitHub repository for every package and let the package owner maintain the license designation and explanations there.
4. Check-in a script we can execute to generate this file on a regular basis to keep it up to date without so much manual overhead

I know that's a lot to look over, but if we are going to do this, I want to make sure that we do it right. Let me know what you think or if I'm missing something. Thanks!

**Comment by AYIDouble** [comment]
@dabutvin 
Thank you for your reply, I went now through all source files in the Web Folder (.cs, .cshtml).
I Made a list of all Licenses and added a disclaimer, that protects you from the case that a license get modified.
The only thing that needs to be done now, is adding all licenses from (https://github.com/dabutvin/ImgBot/blob/master/Web/package-lock.json).
Everything you said makes Sense, the project is still being developed, there's a high change that the list in package-lock.json gets bigger.
I think this is a great Task that can be assigned to a beginner in the future. 😄👍

**Comment by AYIDouble** [comment]
> I think this is a great Task that can be assigned to a beginner in the future. 😄👍

It's a perfect Task for the beginning Hacktoberfest, that is running from the 1. October - 31. October.
https://hacktoberfest.digitalocean.com/

**Pull request closed without merging**
