### PR TITLE
Corrected Grammatical Mistakes

### PR DESCRIPTION
**Pull request by rutujak24**
I have Corrected Grammatical Mistakes in the docs of the project. Looking forward to getting the stickers soon :)

### CODE REVIEW

**Comment by dlemstra** [comment]
Which stickers are you referring to?

**Comment by rutujak24** [comment]
> Which stickers are you referring to?

I am referring to the imgbot stickers which we get by filling the form, merging pr and using imgbot activated on GitHub.

**Comment by dlemstra** [comment]
Which company / organization is promising you that?

**Comment by rutujak24** [comment]
Screenshot_20201124-212941
The imgbot emails itself

**Comment by rutujak24** [comment]
Hey, @dlemstra Thanks for reviewing and merging my PR. I request you to send me ImgBot swags as I have submitted [this form](https://docs.google.com/forms/d/e/1FAIpQLScpL5wT5dsFTXZou49p7_W7Y2sbMeqKulvDrwHQabecc4YF7w/viewform). I would be more than glad to have them. Looking forward :)

**Comment by dlemstra** [comment]
First of all I am not the person that sends the swag. And that form was for people who used the image bot in their project, not for opening a PR here. Not sure if swag is still being send out by the maintainer of this project.

**Comment by rutujak24** [comment]
Yes Sir I do understand it. I am also using the imgbot on my GitHub, whoms screenshots I habe shared earlier. Also this was my contributions without any expectations. Thanks

**Pull request merged**
