### PR TITLE
chore: reverted Magick.NET version

### PR DESCRIPTION
**Pull request by GrigoreMihai**

### CODE REVIEW

**Comment by dlemstra** [comment]
Is it possible to add some kind of testing to make sure that an upgrade doesn't break anything? If I have something that can be used to reproduce this issue I can figure out why this suddenly broke.

**Comment by GrigoreMihai** [comment]
> Is it possible to add some kind of testing to make sure that an upgrade doesn't break anything? If I have something that can be used to reproduce this issue I can figure out why this suddenly broke.

I will think about testing, right now we only test if the image is building successfully but the errors are happening at runtime . You can see the error happening on our image on the `latest` tag here: https://hub.docker.com/layers/165383197/vertigostudio/imgbot-compress/latest/images/sha256-de6952cdadfcc3f1cc882ef4e3c360286f43a3811b601722942a0c27586a9a4f?context=repo . The steps for building this image are the ones from here: https://github.com/imgbot/Imgbot/blob/master/Dockerfile.CompressImages . If you wish you can build the image locally by running: `docker build -f Dockerfile.CompressImages . -t imgbot` from the root of the repository. The beta image from our repository is the version with the previous Magick.NET version (10.1.0) which is working. If it helps debugging the issue is only happening with the docker image, my guess it is that there are more dependencies that we should copy in the resulting image as we currently do here:  https://github.com/imgbot/Imgbot/blob/master/Dockerfile.CompressImages#L9 , but I do not see any dependencies that are added in Magick.NET latest version compared to 10.1.0 . The error that we are getting is the following: `One or more errors occurred. (The type initializer for 'ImageMagick.MagickFormatInfo' threw an exception.) ` . Let me know if you have any idea on how we can fix this or if I can help you with anything regarding this issue, thank you.

**Comment by dlemstra** [comment]
Thanks for all the info that you gave me. I figured out what was causing this. With the `12.0.1` version the libraries are now build on Ubuntu `18.04` instead of `16.04`. And when I check the library with `ldd` inside the container I get this error message:

```
root@e11ee601f192:~/site/wwwroot/bin# ldd Magick.Native-Q16-x64.dll.so
./Magick.Native-Q16-x64.dll.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./Magick.Native-Q16-x64.dll.so)
./Magick.Native-Q16-x64.dll.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by ./Magick.Native-Q16-x64.dll.so)
./Magick.Native-Q16-x64.dll.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./Magick.Native-Q16-x64.dll.so)
        linux-vdso.so.1 (0x00007ffe7275b000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f45e1eda000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f45e1cbd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f45e19b9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45e161a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f45e46d5000)
```

I noticed that a .NET Core 2.1 version of the library was being used and I think an upgrade to at least `3.1` (probably better to directly go for `net6`?) should resolve this issue. But for now it seems to be impossible to upgrade Magick.NET.

**Comment by dlemstra** [comment]
This issue should be resolved with the latest release.

**Comment by GrigoreMihai** [comment]
> This issue should be resolved with the latest release.

Thank you for the update and previous suggestion to upgrade, we also managed to fix this a while back by upgrading to `net6.0` : https://github.com/imgbot/Imgbot/commit/b0ca225b9f19ed9f8433f041fc8320ff96082a84 .

**Pull request merged**
