### PR TITLE
Contribution to IMGBOT

### PR DESCRIPTION
**Pull request by kartik251**
All the code for Imgbot is available on GitHub. We will gladly accept contributions for the service, the website, and the documentation. This is where you can find out how to get set up to run locally as well as detailed information on exactly how Imgbot works.

https://imgbot.net/docs#contributing

### CODE REVIEW

**Comment by dlemstra** [comment]
What are you trying to do?

**Comment by githubmansi50** [comment]
NA

**Comment by keshavpawar** [comment]
.

**Comment by anandtiwaari** [comment]
sahi hai

**Pull request closed without merging**
