### PR TITLE
(GitHub CI) Bump actions/checkout version in workflows

### PR DESCRIPTION
**Pull request by ArjunSharda**

### CODE REVIEW

**Comment by ArjunSharda** [comment]
> Would you mind adding a `dependabot.yml` file in the `.github` folder with the following content also:
> 
> 
> 
> ```yaml
> 
> version: 2
> 
> updates:
> 
>   - package-ecosystem: "github-actions"
> 
>     directory: "/"
> 
>     schedule:
> 
>       interval: "weekly"
> 
> ```
> 
> 
> 
> That would make sure that these actions get updated automatically.

Sure I forgot about this in root. Will do when I can

**Comment by ArjunSharda** [comment]
Bumping up

**Comment by ArjunSharda** [comment]
Please review tomorrow @dlemstra

**Comment by dlemstra** [comment]
Sorry for the late response but I was thinking that one of the owners of this repository would pick up this pull request. Going to merge it now.

**Comment by dlemstra** [comment]
Just a remark in case you open a pull request like this in another repository. The `dependabot.yml` file should be in the `.github` folder and not in the `.github/workflows` folder. I fixed this in a follow up pull request.

**Comment by ArjunSharda** [comment]
Thank you. Will make sure.

**Pull request merged**
