### PR TITLE
swap Directory.EnumerateFiles for regex for more flexibility (fix #160)

### LINKED ISSUE #160: Upgrade Directory.EnumerateFiles to something more flexible
Right now we use Directory.EnumerateFiles to process the ignoredfiles for the `.imgbotconfig`
This can be really inflexible for common `*` patterns that you would assume you can use.

 - Code: https://github.com/dabutvin/ImgBot/blob/master/CompressImagesFunction/ImageQuery.cs
 - Doc: https://imgbot.net/docs#ignoring-files (https://github.com/dabutvin/ImgBot/blob/master/Docs/ignoring-files.md)
 - Tests: https://github.com/dabutvin/ImgBot/blob/master/Test/ImageQueryTests.cs

Maybe something like this would be better: https://github.com/kthompson/glob

### PR DESCRIPTION
**Pull request by dabutvin**
Tried a few globbing libraries, but none of them provided the flexibility I was looking for

### CODE REVIEW

**Comment by SaberUK** [comment]
I think the documentation in the README needs to be updated as it still shows the old way:

https://github.com/dabutvin/ImgBot/blob/master/README.md#configuration

**Comment by dabutvin** [comment]
@SaberUK this update was meant to be backwards compatible, so these should still be working.

Are you having some trouble with them somewhere?

**Comment by SaberUK** [comment]
@dabutvin I'm using [this config](https://github.com/inspircd/inspircd.github.com/blob/043ee426acd35b3895af51b9dcb6f2720b2a6a5f/.imgbotconfig) which contains valid glob patterns but ImgBot [seems to be ignoring it](https://github.com/inspircd/inspircd.github.com/pull/16).

**Comment by dabutvin** [comment]
I see.

I just forked and tried updating and got it to work with this:

```json

{
    "ignoredFiles": [
	"api/2.0/**/*.png",
	"api/3.0/**/*.png"
    ]
}
```

https://github.com/dabutvin/inspircd.github.com/pull/1

I guess it is still a little less flexible than it could be.

**Comment by SaberUK** [comment]
[That seems to work](https://github.com/inspircd/inspircd.github.com/pull/17). Thanks for the help.

**Comment by dabutvin** [comment]
Glad it worked out.

 https://globster.xyz/ is a really good resource for playing with glob expressions.

You can see the highlight on the left when you type

**Pull request merged**
